All files changes new project
akashipov/go-musthave-diploma-tpl pull request #7
Opened 2024-01-11 16:39 UTC by akashipov

2024-01-12 22:24 UTC, capsulated requested changes
Ну всё "в одной куче". Можно вообще в одном файле main.go конечно сделать...

Всё в самый последний момент и в таком виде - не очень хорошо, в production за такое могут уволить

Я напишу тебе в директ ещё

2024-01-12 22:24 UTC, capsulated commented on cmd/.DS_Store
Удалить и в .gitignore добавить

2024-01-12 22:24 UTC, capsulated commented on cmd/gophermart/main.go
> +func runUpdatingStatusOrders(w *sync.WaitGroup, ready chan bool, done chan bool) {
это в internal перенести

2024-01-12 22:24 UTC, capsulated commented on cmd/gophermart/main.go
> +	query := "SELECT order_id, name FROM orders WHERE status != 'PROCESSED' and status != 'INVALID'"
Для запросов нужно создать отдельный пакет с подключением к базе. Добавит интерфейс

2024-01-12 22:24 UTC, capsulated commented on cmd/gophermart/main.go
> +loop:
goto не надо

для бесконечного цикла - отдельную функцию

2024-01-12 22:24 UTC, capsulated commented on cmd/gophermart/main.go
> +			for rows.Next() {
методы постгреса в отдельный пакет

2024-01-12 22:24 UTC, capsulated commented on cmd/gophermart/main.go
> +func run(srv *http.Server, done chan bool, ready chan bool, log *zap.SugaredLogger) {
Сервер в отдельный пакет2

2024-01-12 22:24 UTC, capsulated commented on cmd/gophermart/main.go
> +		sigint := make(chan os.Signal, 1)
Сигналы тогда в конец main в и select с чтением сигнала. Далее в кейсах завершение всех рутин приложения

2024-01-12 22:24 UTC, capsulated commented on internal/.DS_Store
удалить и в гитигнор

2024-01-12 22:24 UTC, capsulated commented on internal/general/logger.go
> +func WithLogging(h http.Handler, s *zap.SugaredLogger) func(w http.ResponseWriter, r *http.Request) {
Нужно отдельный пакет для middleware

2024-01-12 22:24 UTC, capsulated commented on internal/general/utils.go
> +		if err != nil {
`if/else` оптимизировать с помощью guard clauses и [тут](https://go.dev/wiki/CodeReviewComments#indent-error-flow) ещё есть метод.  guard clauses - гугли

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +func GzipHandle(next http.Handler, log *zap.SugaredLogger) http.Handler {
middleware отдельным пакетом (смотри репозиторий chi для примера)

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +func Authontefication(w http.ResponseWriter, request *http.Request) {
Орфографические ошибки в нейминге надо тоже фиксить

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +			} else {
ветвление if/else упрощать (как в коментарии выше)

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +					// delete old version
Ну это вообще беда, такое читать невозможно, if/else дикие, так нельзя. Комментарии такие тоже удалить надо

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +					} else {
Обязательно оптимизировать

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +type Statuses int64
по файлам хотябы раскидать

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +	query := "SELECT order_id, name, status, accrual, created_time FROM orders WHERE name = $1 ORDER BY created_time"
в хендлерах запросы ни в коем случае, должно быть в другом пакете хранилки

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers.go
> +	query := "SELECT order_id, sum, processed_at FROM withdrawals WHERE name = $1"
обязательно отделить запросы от хендлеров

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers_utils.go
> +func GetWallet(request *http.Request, name string) (*Balance, error) {
это всё должно быть распределено по пакетам и составным типам с методами

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/handlers_utils.go
> +func CheckAuthoriazation(w http.ResponseWriter, request *http.Request, tkn string) (string, error) {
Хендлеры не должны содержать дополнительный параметр. Для этого надо создать структуру с необходимыми полями (токен, указатель на хранилку, указатель на логгер и тп) и обращаться к ним через ресивер в назначенных типу методах (смотри мой вебинар по интерфейсы - там есть это на третьем слайде, вроде)

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/storage.go
> +	_, err = DB.Exec(
`init.sql` лучше сделать, прочитать и запустить

2024-01-12 22:24 UTC, capsulated commented on internal/gophermarket/storage.go
> +type RegisterData struct {
типы распределить по пакетам (папкам)

2024-01-13 11:59 UTC, akashipov commented on internal/gophermarket/storage.go
> +type RegisterData struct {
поправил

2024-01-13 11:59 UTC, akashipov commented on internal/gophermarket/storage.go
> +	_, err = DB.Exec(
сделал

2024-01-13 12:00 UTC, akashipov commented on internal/gophermarket/handlers_utils.go
> +func CheckAuthoriazation(w http.ResponseWriter, request *http.Request, tkn string) (string, error) {
это не хендлер... это вспомогательная функция для хендлера, но я попытаюсь сейчас сделать что то с этим

2024-01-13 12:09 UTC, akashipov commented on cmd/gophermart/main.go
> +func runUpdatingStatusOrders(w *sync.WaitGroup, ready chan bool, done chan bool) {
сделал

2024-01-15 23:08 UTC, akashipov commented on internal/gophermarket/handlers.go
> +	query := "SELECT order_id, sum, processed_at FROM withdrawals WHERE name = $1"
отделено

2024-01-15 23:08 UTC, akashipov commented on cmd/gophermart/main.go
> +			for rows.Next() {
отделено

2024-01-15 23:09 UTC, akashipov commented on cmd/gophermart/main.go
> +	query := "SELECT order_id, name FROM orders WHERE status != 'PROCESSED' and status != 'INVALID'"
добавил

2024-01-17 22:18 UTC, capsulated requested changes
Да, уже намного лучше, но по оставшимся комментам надо бы исправить. И тесты, минимальный базовый функционал с ордерами покрыть

2024-01-17 22:18 UTC, capsulated commented on internal/gophermarket/handlers.go
> +func ServerRouter(log *zap.SugaredLogger) http.Handler {
Как обсуждали на 1-1, про [принимаем интерфейс, возвращаем экземпляр](https://tutorialedge.net/golang/accept-interfaces-return-structs/) (указатель на тип - структуру)

Стандартный go-way подход:
```golang
// Объявляем кастомный составной тип - объект (аналог класса)
type Router struct { ... }

// Конструктор типа (конструктор класса)
func NewRouter(<внедрение_зависимостей_в_конструкторе>) *Router { ... }

// Методы типа (аналогично методам классов в питоне), для примера:
func (r *Router) RebindAuthenticationKey() { ... }
```

2024-01-17 22:18 UTC, capsulated commented on internal/gophermarket/handlers.go
> +	router := chi.NewRouter()
Пример конструктора в chi - `chi.NewRouter()`. Бери код с библиотек, тот же самый [Prometheus](https://github.com/prometheus) смотри и изучай code style

2024-01-17 22:18 UTC, capsulated commented on internal/gophermarket/handlers.go
> +func GzipHandle(next http.Handler, log *zap.SugaredLogger) http.Handler {
🤷

2024-01-17 22:18 UTC, capsulated commented on internal/gophermarket/orders/update.go
> +loop:
loop всё же убрать и поменьше `else`, так как читать неудобно очень

2024-01-17 22:18 UTC, capsulated commented on internal/gophermarket/storage/orders/orders.go
> +package orders
Да, круто, что вынес, но скорее на глобальный уровень выносить нужно, так как модели (бизнес логика) могут использоваться почти во всех пакетах

Про различные подходы реализации моделей бизнес логики можно почитать [тут](https://habr.com/ru/articles/718916/), к сожалению, на примере PHP Symphony, но к изучению прям обязательно

2024-01-18 19:01 UTC, akashipov commented on internal/gophermarket/orders/update.go
> +loop:
если я убираю loop то там помечается код как unreachable, я подозреваю что break будет работать на select и не будет выходить из цикла как надо

код который w.Done()

2024-01-18 19:02 UTC, akashipov commented on internal/gophermarket/orders/update.go
> +loop:
я увидел только один else плохо понимаю что еще нужно убрать

2024-01-18 19:02 UTC, akashipov commented on internal/gophermarket/orders/update.go
> +loop:
остальное все просто обработка ошибок

2024-01-18 19:03 UTC, akashipov commented
https://github.com/akashipov/go-musthave-diploma-tpl/pull/7#discussion_r1456550797
вот тут не понимаю что нужно сделать... функция не используется так как автотесты не работают с этим нормально

2024-01-18 19:34 UTC, akashipov commented
https://github.com/akashipov/go-musthave-diploma-tpl/pull/7#discussion_r1456532421 не понимаю что здесь должен сделать, и во многих местах я не могу комментировать, там нет обсуждения ниже какого то

2024-01-18 19:35 UTC, akashipov commented
https://github.com/akashipov/go-musthave-diploma-tpl/pull/7#discussion_r1456532163?

перене, распределил все. создал отдельный класс сервер, который всем этим уже занимается

2024-01-22 10:49 UTC, capsulated approved these changes
Пару комментариев добавил, посмотри для ознакомления. Работу принимаю, так как уже совсем все дедлайны прошли 😬

Конечно, намного лучше, чем самое первое ревью, но всё равно осталось ещё, что порефакторить... Штож))

2024-01-22 10:49 UTC, capsulated commented on cmd/gophermart/main.go
> +	s := server.Server{}
Тут вызов парсинга конфигов должен быть, по-хорошему...

2024-01-22 10:49 UTC, capsulated commented on internal/gophermarket/server/server.go
> +func (s *Server) GetLogger() (*zap.SugaredLogger, error) {
Обычно конструктор добавляется (возвращает указатель на экземпляр объекта):
```
func NewServer(log *logger) *Server {
   ...
}
```

2024-01-22 10:49 UTC, capsulated commented on internal/gophermarket/server/server.go
> +loop:
Луп так и не убрал) Лучше не юзать его, это должны быть совсем исключительные случаи. На интервью такого не оценят))

2024-01-22 13:39 UTC, akashipov commented on internal/gophermarket/server/server.go
> +loop:
дед код появляется если убрать, логика меняется сильно

2024-01-22 13:40 UTC, merged